# Generated by Django 4.2.5 on 2023-11-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakevarient',
            name='weight',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
