# Generated by Django 4.2.5 on 2023-11-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_alter_cakevarient_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakecategory',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
